### ISSUE TITLE
Initial schematic TODO list

### ISSUE THREAD

**Issue by kongr45gpen** [RoboticExplorationLab/Chipsat-Hardware#2]
- [x] MCU
- [x] MCU power supply
- [x] MCU RST switch/boot0
- [x] MCU crystals
- [x] H/W watchdog (2xGPIO)
- [x] Hi-pow select for USB
- [x] ~~RTC (`I2C3`)~~
- [x] SD Card (`SDMMC2`)
- [x] UHF Radio (`SPI1`, 2xGPIO)
- [x] Flash Storage (`SPI3`)
- [x] USB Connection (`USB_OTG_HS`) + Regulator
- [x] IMU (`USART3`, 2xGPIO)
- [x] Status LED (3xGPIO)
- [x] DBG connector (`LPUART`)
- [x] ~~I2C bus protection (???)~~
- [x] ~~SPI bus protection (???)~~
- [x] Solar cells + MQTT
- [x] Battery Current Draw Sensor (`I2C1`)
- [x] Light sensor (`I2C2`)
- [x] Camera + LDOs (`DCMI`, 1xGPIO, `TIM4`, `I2C4`)
- [x] Burn wires
- [x] Deployment switch
- [x] Heaters
